swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains the needed endpoints for the v2
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction API
      description:  API for retrieving all of the transactions of the selected month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: query
          name: month
          type: string
          description: Year and number of the month from which we want to retrieve the transactions
          default: "2023-11"
          required: true
      responses:
        '200':
          description: Transactions retrieved Successfully
          schema:
            $ref: '#/definitions/ArrayOfTransactionResponse'
        '401':
          description: You need to be authentified to access to these data
        '403':
          description: You don't have the permission to access these data
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      produces:
        - application/json
      tags:
        - Transactions Module
      summary: Create a transaction (should not be implemented)
      description: API to create a new transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        '201':
          description: Transaction added successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Bad request, make sure the object you are trying to create match the syntax
        '401':
          description: You need to be authentified to access to add a new transaction
        '403':
          description: You don't have the permission to add a new transaction
        '500':
          description: Internal Server Error
  /user/transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Retrieve one transaction
      description:  API to fetch one of the transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: id
          in: path
          description: transaction id
          required: true
          type: integer
      responses:
        '200':
          description: Transaction retrieved Successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Bad request, transaction ID must be an integer and larger than 0
        '401':
          description: You need to be authentified to access to these data
        '403':
          description: You don't have the permission to access these data
        '404':
          description: A transaction with the specified ID was not found
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Modify a transaction
      description: API for updating a transaction
      parameters:
        - name: id
          in: path
          description: transaction id
          required: true
          type: integer
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: You need to be authentified to modify this transaction
        '403':
          description: You don't have the permission to modify this transaction
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  # SHOULD NOT BE IMPLEMENTED
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Delete a transaction (should not be implemented)
      description: API for deleting permanently the selected transaction
      parameters:
        - in: path
          name: id
          description: id of the transaction that will be deleted
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      responses:
        '200':
          description: Transaction deleted successfully
        '401':
          description: You need to be authentified to delete this transaction
        '403':
          description: You don't have the permission to delete this transaction
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionResponse:
    type: object
    properties: 
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties: 
          transaction:
            type: object
            properties:
              schema:
                $ref: '#/definitions/TransactionFull'
  ArrayOfTransactionResponse:
    type: object
    properties: 
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties: 
          transaction:
            type: object
            properties:
              schema:
                $ref: '#/definitions/ArrayOfTransactions'
  ArrayOfTransactions:
    type: array
    items:
      $ref: '#/definitions/TransactionFull'
  Transaction:
    type: object
    properties:
      date:
        type: string
        example: "November 11, 2023"
      month:
        type: string
        example: "2023-11"
      description:
        type: string
        example: "Golden Sun Bakery"
      amount:
        type: number
        example: "5.05"
      balance:
        type: number
        example: "2082.79"
      transactionType:
        type: string
        example: "Electronic"
      category:
        type: string
        example: "Food"
      notes:
        type: string
        example: "Buying dinner to mom"
  TransactionFull:
    type: object
    properties:
      idUser:
        type: string
        example: "tonystark"
      id:
        type: string
        example: "tr1"
      date:
        type: string
        format: date
        example: "November 11, 2023"
      month:
        type: string
        example: "2023-11"
      description:
        type: string
        example: "Golden Sun Bakery"
      amount:
        type: number
        example: "5.05"
      balance:
        type: number
        example: "2082.79"
      transactionType:
        type: string
        example: "Electronic"
      category:
        type: string
        example: "Food"
      notes:
        type: string
        example: "Buying dinner to mom"